import "./global.css";
import { LoadingProvider } from "./lib/loading-context";
import { GlobalProgressBar } from "./components/global-progress-bar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LoadingProvider>
          <GlobalProgressBar />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
